In [1]:
import numpy as np
import pandas as pd
import re
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_excel('https://www.sharkattackfile.net/spreadsheets/GSAF5.xls')

In [3]:
df.head()

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,Unnamed: 11,Time,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,2024-10-14 00:00:00,2024.0,Unprovoked,Honduras,Tela,Atlantida,Swimming,Roberto Carlose Bu Mejia,M,38,Back and thigh extensive tissue loss,N,?,Bull shark,Georgienne Bradley: Daily Mail UK: FTN News.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-10-11 00:00:00,2024.0,Unprovoked,USA,Florida,Brevard County Orlando,Surfing,Teddy Witteman,M,16,Bite to left arm,N,?,Bull shark 6ft,Todd SmithFlorida today: News 4:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-09-17 00:00:00,2024.0,Unprovoked,Honduras,Trujillo Colon,Puerto Castillo,Diving for shellfish,Fernando Mendoza Ocampo,M,33,Bite to left leg,N,?,Bull shark 6-7ft,Daily Mail UK: The Sun UK: The World Watch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-09-16 00:00:00,2024.0,Unprovoked,Morocco,Southern Morocco,West of Dakhla,Swimming - jumped off yacht,German Tourist,F,30,Leg severed,Y,1600hr,Reportedly a Great White,Andy Currie: Moroccan World News: Sky News,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-08-26 00:00:00,2024.0,Unprovoked,Jamaica,Montego Bay,Falmouth,Spearfishing,Jahmari Reid,M,16,Head right arm and leg severed,Y,?,Reportedly Tiger Shark,Todd Smith: Daily Mail UK: Sky News: People .com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(6973, 23)

In [5]:
df['Country'].value_counts()

Country
USA                           2551
AUSTRALIA                     1481
SOUTH AFRICA                   597
NEW ZEALAND                    144
PAPUA NEW GUINEA               136
                              ...
GABON                            1
ANDAMAN / NICOBAR ISLANDAS       1
MALDIVE ISLANDS                  1
NICARAGUA                        1
CEYLON (SRI LANKA)               1
Name: count, Length: 235, dtype: int64

In [6]:
df_usa = df[df['Country']=='USA']

In [7]:
df_florida = df_usa[df_usa["State"]=='Florida']

In [8]:
df_florida.shape

(1183, 23)

In [9]:
df_florida.reset_index(drop=True, inplace=True)
df_florida.columns = [c.lower().strip() for c in df_florida.columns.values.tolist()]
df_florida.shape

(1183, 23)

In [10]:
df_florida.head()

,date,year,type,country,state,location,activity,name,sex,age,injury,unnamed: 11,time,species,source,pdf,href formula,href,case number,case number.1,original order,unnamed: 21,unnamed: 22
0,2024-10-11 00:00:00,2024.0,Unprovoked,USA,Florida,Brevard County Orlando,Surfing,Teddy Witteman,M,16,Bite to left arm,N,?,Bull shark 6ft,Todd SmithFlorida today: News 4:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-07-08 00:00:00,2024.0,Unprovoked,USA,Florida,Ponce de Leon Inlet Volusia County,Diving into Water,Dempsey Manhart,M,14,Lower left leg injury,N,11hr15,4-5ft Blacktip shark,Miami Herald,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-07-05 00:00:00,2024.0,Unprovoked,USA,Florida,New Smyrna Beach,Wading,Not stated,M,26,Minor injury to left foot,N,16hr15,Not specified,Sacbee Fox 35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-07-04 00:00:00,2024.0,Unprovoked,USA,Florida,New Smyrna Beach Beach Access 14 Volusia County,Swimming,Not released,M,NaN,Bite to left leg,N,1100hr,6ft shark,Brietbart .com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-06-07 00:00:00,2024.0,Unprovoked,USA,Florida,Rosemary Beach Walton County,Swimming,Elisabeth Foley,F,45,Significant injuries to pelvic and abdominal r...,N,13h15,Not specified Bull shark highly suspect,12onyourside.com: News Channel 7wjhg : Al.Com:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#Removing useless columns, including the last two
columns_to_drop = [df_florida.columns[-1], df_florida.columns[-2]]
# Check if 'Country' and 'State' columns exist before dropping
if 'country' in df_florida.columns:
    columns_to_drop.append('country')
if 'state' in df_florida.columns:
    columns_to_drop.append('state')

df_florida = df_florida.drop(columns=columns_to_drop, axis=1)
df_florida = df_florida.drop(['year', df_florida.columns[9], "name"] + list(df_florida.columns[-7:]), axis=1)
df_florida.shape

(1183, 9)

In [12]:
df_florida.head()

,date,type,location,activity,sex,age,injury,time,species
0,2024-10-11 00:00:00,Unprovoked,Brevard County Orlando,Surfing,M,16,Bite to left arm,?,Bull shark 6ft
1,2024-07-08 00:00:00,Unprovoked,Ponce de Leon Inlet Volusia County,Diving into Water,M,14,Lower left leg injury,11hr15,4-5ft Blacktip shark
2,2024-07-05 00:00:00,Unprovoked,New Smyrna Beach,Wading,M,26,Minor injury to left foot,16hr15,Not specified
3,2024-07-04 00:00:00,Unprovoked,New Smyrna Beach Beach Access 14 Volusia County,Swimming,M,NaN,Bite to left leg,1100hr,6ft shark
4,2024-06-07 00:00:00,Unprovoked,Rosemary Beach Walton County,Swimming,F,45,Significant injuries to pelvic and abdominal r...,13h15,Not specified Bull shark highly suspect

In [13]:
df_florida.shape

(1183, 9)

In [14]:
#Victor
def standardize_string(column: pd.Series):
  clean_column = column.str.lower().str.strip().apply(str)
  return clean_column

def standardize_activity(activity: str):
  """
  Place every activity in a common category based on the words in this activity.
  """
  if activity=='nan':
    return 'unknown'

  activities = ['surfing', 'swimming', 'wading', 'fishing', 'standing', 'spearfishing', 'boarding', 'snorkeling', 'diving', 'walking', 'bathing', 'floating']
  standardized_activity = "other"
  for activ in activities:
    if activ in activity:
      standardized_activity = activ
      break
  #if standardized_activity == "other":
    #print(activity)
  return standardized_activity
df_florida['activity'] = standardize_string(df_florida['activity'])
#df_florida['activity'].value_counts().head(20)
df_florida.shape

(1183, 9)

In [15]:
df_florida['activity'] = df_florida['activity'].apply(standardize_activity)
df_florida['activity'].value_counts().head(10)

activity
surfing     463
swimming    177
fishing     116
other        87
wading       86
unknown      75
diving       45
standing     45
boarding     39
floating     14
Name: count, dtype: int64

In [16]:
#Victor

def standardize_type(attack_type: str):
  if attack_type != 'unprovoked' and attack_type != 'provoked':
    return 'unknown'
  return attack_type

df_florida['type'] = standardize_string(df_florida['type'])
df_florida['type'] = df_florida['type'].apply(standardize_type)
#df_florida['type'].value_counts()
df_florida['location'].value_counts().head(20)

location
New Smyrna Beach, Volusia County                   191
Daytona Beach, Volusia County                       31
Ponce Inlet, Volusia County                         28
Melbourne Beach, Brevard County                     20
Cocoa Beach, Brevard  County                        18
Jacksonville Beach, Duval County                    13
Cocoa Beach, Brevard County                         13
Juno Beach, Palm Beach County                       12
Ponce Inlet, New Smyrna Beach, Volusia County       12
Palm Beach, Palm Beach County                       11
Ormond Beach, Volusia County                        11
Singer Island, Riviera Beach, Palm Beach County     10
Florida Keys, Monroe County                         10
Vero Beach, Indian River County                     10
Florida Keys                                         9
Sanibel Island, Lee County                           8
Jensen Beach, Martin County                          8
Daytona Beach Shores, Volusia County                 8
Jacksonville, Duval County                           7
Pensacola Bay, Escambia County                       7
Name: count, dtype: int64

In [17]:
#Victor
df_florida['location'] = standardize_string(df_florida['location'])

def standardize_location(location: list):
  """
  Return a [location, county] list based on the words in this location.
  """

  counties = ['volusia county', 'brevard county', 'martin county', 'duval county', 'palm beach county', 'monroe county', 'indian river county', 'lee county']
  locations = ['new smyrna beach', 'daytona beach', 'ponce inlet', 'melbourne beach', 'cocoa beach', 'jacksonville beach', 'florida keys', 'juno beach', 'ormond beach', 'palm beach', 'riviera beach']
  loc = "other"
  county = "other"

  if len(location)==1:

    if location[0] == 'nan':

      return ['unknown', 'unknown']

    else:
      loc = 'other'
      county = 'other'
      loca = location[0]

      for l in locations:
        if l in loca:
          loc = l
      for c in counties:
        if c in loca:
          county = c


  elif len(location) ==2:

    loc, county = location[0], location[1]

    for l in locations:
      if l in loc:
        loc = l

    for c in counties:
      if c in loc:
        county = c

  elif len(location) > 2:

    loc, county = location[0], location[-1]

    for l in locations:
      if l in loc:
        loc = l

    for c in counties:
      if c in loc:
        county = c

  return [loc, county]

#df_florida['location'].value_counts().head()

test_df = pd.DataFrame([standardize_location(x.split(',')) for x in df_florida['location']], columns=['precise_location', 'county'])

for i, (loc, county) in enumerate(test_df.values):
  if loc not in ('other', 'unknown') and county in ('other', 'unknown'):

    if loc == 'new smyrna beach' or loc == 'ormond beach' or loc == 'daytona beach': test_df.loc[i, "county"] = 'volusia county'
    if loc == 'florida keys': test_df.loc[i, "county"] = 'monroe county'
    if loc == 'riviera beach' or loc == 'palm beach' or loc == 'juno beach': test_df.loc[i, "county"] = 'palm beach county'

df_florida = pd.concat([df_florida, test_df], axis=1, join='inner')
df_florida.head()

,date,type,location,activity,sex,age,injury,time,species,precise_location,county
0,2024-10-11 00:00:00,unprovoked,brevard county orlando,surfing,M,16,Bite to left arm,?,Bull shark 6ft,other,brevard county
1,2024-07-08 00:00:00,unprovoked,ponce de leon inlet volusia county,diving,M,14,Lower left leg injury,11hr15,4-5ft Blacktip shark,other,volusia county
2,2024-07-05 00:00:00,unprovoked,new smyrna beach,wading,M,26,Minor injury to left foot,16hr15,Not specified,new smyrna beach,volusia county
3,2024-07-04 00:00:00,unprovoked,new smyrna beach beach access 14 volusia county,swimming,M,NaN,Bite to left leg,1100hr,6ft shark,new smyrna beach,volusia county
4,2024-06-07 00:00:00,unprovoked,rosemary beach walton county,swimming,F,45,Significant injuries to pelvic and abdominal r...,13h15,Not specified Bull shark highly suspect,other,other

In [18]:
#Camil

#Cleaning for sex column
def clear_sex(sex):
    if pd.isna(sex):
        return "F"

    sex = sex.strip().upper()

    if sex == "F":
        return "F"
    elif sex == "N" or sex == "LLI":
        return "F"
    else:
        return "M"


df_florida["sex"] = df_florida["sex"].apply(clear_sex)


#Cleaning for Age column
df_florida["age"] = df_florida['age'].ffill()
df_florida["age"] = df_florida["age"].astype(str).str.extract('(\d+)').astype(float)

df_florida = df_florida.dropna(subset=['age'])

#Add an Age group column
def categorize_age(age):
    if age > 60: return 'Senior'
    if age > 18: return 'Adult'
    if age > 12: return 'Teens'
    else:
      return 'Child'

df_florida['age_group'] = df_florida['age'].apply(categorize_age)


#Date to datetime
def clean_date_prefix(date_value):
  prefixes = ["Reported", "Eearly", "Before", "Fall"]
  for prefix in prefixes:
    if date_value.startswith(prefix):
      return date_value[len(prefix):].strip()
    return date_value

df_florida = df_florida.dropna(subset=['date'])

df_florida['date'] = df_florida['date'].astype(str).apply(clean_date_prefix)

df_florida['date'] = pd.to_datetime(df_florida['date'], format='mixed', dayfirst=True, errors='coerce')

<ipython-input-18-f45b4174939a>:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_florida['age_group'] = df_florida['age'].apply(categorize_age)

In [19]:
df_florida.shape

(1165, 12)

In [20]:
# cleaning the data for "Time" into 00h00 format

def standardize_time_format(time_str):
    time_str = str(time_str).strip().lower()

    # Define regex patterns for matching time formats
    patterns = [
        r'(\d{1,2})h(\d{2})',  # matches '12h30', '11h15'
        r'(\d{1,2})h',          # matches '9h', '14h'
        r'(\d{1,2}):(\d{2})',   # matches '11:30', '14:05'
        r'(\d{4})hr',           # matches '1600hr', '1100hr'
        r'(\d{4})',             # matches '1600', '1300' (4 digits)
    ]

    for pattern in patterns:
        match = re.fullmatch(pattern, time_str)
        if match:
            if len(match.groups()) == 2:  # e.g. '12h30'
                hours, minutes = match.groups()
                return f"{int(hours):02}h{int(minutes):02}"
            elif len(match.groups()) == 1:  # e.g. '9h' or '1600hr'
                if 'h' in time_str and 'hr' not in time_str:
                    hours = match.group(1)
                    return f"{int(hours):02}h00"
                else:
                    # Handling 4-digit format like '1600'
                    hours = match.group(1)[:2]
                    minutes = match.group(1)[2:]
                    return f"{int(hours):02}h{int(minutes):02}"

    return 'unknown'
def time_category(time):
  time = str(time)
  if time[0:2].isdigit():
    hour = int(time[0:2])
    if hour > 20 or hour < 7:
      return 'night'
    elif hour >= 12:
      return 'afternoon'
    elif hour >= 7:
      return 'morning'

  return 'unknown'

def clean_and_standardize_time(df, column_name):
    series = df[column_name] #Fixed: Removed extra indent
    series = series[~series.isin(["?", "", np.nan])]

    cleaned_series = series.apply(standardize_time_format)

    #cleaned_series = cleaned_series.dropna()

    df[column_name] = cleaned_series.reset_index(drop=True)
    df[column_name] = df[column_name].apply(time_category)

    #df = df[df[column_name].notna()]

    return df

df_florida = clean_and_standardize_time(df_florida, "time")
df_florida.head()

,date,type,location,activity,sex,age,injury,time,species,precise_location,county,age_group
0,2024-10-11,unprovoked,brevard county orlando,surfing,M,16.0,Bite to left arm,unknown,Bull shark 6ft,other,brevard county,Teens
1,2024-07-08,unprovoked,ponce de leon inlet volusia county,diving,M,14.0,Lower left leg injury,unknown,4-5ft Blacktip shark,other,volusia county,Teens
2,2024-07-05,unprovoked,new smyrna beach,wading,M,26.0,Minor injury to left foot,morning,Not specified,new smyrna beach,volusia county,Adult
3,2024-07-04,unprovoked,new smyrna beach beach access 14 volusia county,swimming,M,26.0,Bite to left leg,afternoon,6ft shark,new smyrna beach,volusia county,Adult
4,2024-06-07,unprovoked,rosemary beach walton county,swimming,F,45.0,Significant injuries to pelvic and abdominal r...,morning,Not specified Bull shark highly suspect,other,other,Adult

In [21]:
# Function to classify shark species into size groups
def classify_size(species):
    small_species = ['Requiem shark', 'Mako shark']  # Example small species
    medium_species = ['Tiger shark', 'Hammerhead shark']  # Example medium species
    large_species = ['Great white shark', 'Bull shark']  # Example large species
    not_specified = ['Not Specified']

    if species in small_species:
        return 'Small'
    elif species in medium_species:
        return 'Medium'
    elif species in large_species:
        return 'Large'
    elif species in not_specified:
        return 'Unknown'
    else:
        return 'Unknown'

# Apply the size classification function
df_florida['size group'] = df_florida['species'].apply(classify_size)

# Display the updated DataFrame
df_florida.head(20)

,date,type,location,activity,sex,age,injury,time,species,precise_location,county,age_group,size group
0,2024-10-11,unprovoked,brevard county orlando,surfing,M,16.0,Bite to left arm,unknown,Bull shark 6ft,other,brevard county,Teens,Unknown
1,2024-07-08,unprovoked,ponce de leon inlet volusia county,diving,M,14.0,Lower left leg injury,unknown,4-5ft Blacktip shark,other,volusia county,Teens,Unknown
2,2024-07-05,unprovoked,new smyrna beach,wading,M,26.0,Minor injury to left foot,morning,Not specified,new smyrna beach,volusia county,Adult,Unknown
3,2024-07-04,unprovoked,new smyrna beach beach access 14 volusia county,swimming,M,26.0,Bite to left leg,afternoon,6ft shark,new smyrna beach,volusia county,Adult,Unknown
4,2024-06-07,unprovoked,rosemary beach walton county,swimming,F,45.0,Significant injuries to pelvic and abdominal r...,morning,Not specified Bull shark highly suspect,other,other,Adult,Unknown
5,2023-11-05,unprovoked,"juno beach, palm beach county",swimming,M,66.0,Lacerations to right forearm,morning,NaN,juno beach,palm beach county,Senior,Unknown
6,2023-09-12,unknown,"new smyrna beach, volusia county",surfing,M,38.0,Llacerations to face and chin,morning,NaN,new smyrna beach,volusia county,Adult,Unknown
7,2023-09-11,unprovoked,"satellite beach, brevard county",surfing,M,38.0,Bite to lower back,afternoon,NaN,satellite beach,brevard county,Adult,Unknown
8,2023-09-04,unprovoked,"ponce inlet, volusia county",surfing,M,30.0,Left hand bitten,afternoon,NaN,ponce inlet,volusia county,Adult,Unknown
9,2023-09-04,unprovoked,"ponce inlet, volusia county",wading,F,37.0,Right foot bitten,afternoon,NaN,ponce inlet,volusia county,Adult,Unknown
10,2023-07-31,unprovoked,"new smyrna beach, volusia county",surfing,M,22.0,Ankle injured,afternoon,NaN,new smyrna beach,volusia county,Adult,Unknown
11,2023-07-30,unprovoked,"anna maria island, manatee county",fishing,M,22.0,Lower leg bitten,morning,NaN,anna maria island,manatee county,Adult,Unknown
12,2023-07-29,unprovoked,tampa bay,swimming,F,26.0,Superficial injuries to abomen and thighs,afternoon,NaN,other,other,Adult,Unknown
13,2023-07-15,unprovoked,new smyrna beach,other,M,49.0,Superficial injury to back,afternoon,NaN,new smyrna beach,volusia county,Adult,Unknown
14,2023-07-14,unprovoked,new smyrna beach,surfing,M,21.0,Severe injury to foot,unknown,NaN,new smyrna beach,volusia county,Adult,Unknown
15,2023-06-23,unprovoked,"cocoa beach, brevard county",swimming,F,2.0,Multiple puncture wounds to right thigh,morning,NaN,cocoa beach,brevard county,Child,Unknown
16,2023-06-23,unprovoked,"flamingo marina, homestead, miami-dade county",fishing,M,2.0,Hand bitten,afternoon,NaN,flamingo marina,miami-dade county,Child,Unknown
17,2023-05-19,provoked,"flagship drive, summerland key, monroe county",fishing,M,35.0,PROVOKED INCIDENT Hooked shark bit his foot,morning,NaN,flagship drive,monroe county,Adult,Unknown
18,2023-05-18,unprovoked,"marathon, monroe county",fishing,M,20.0,,afternoon,NaN,marathon,monroe county,Adult,Unknown
19,2023-05-11,unprovoked,"fort pierce, st. lucie county",other,F,13.0,Multiple bites,afternoon,"Bull shark, 4'",fort pierce,st. lucie county,Teens,Unknown